# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 23:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='app/static/')),
                ('imgReferencia', models.ImageField(upload_to='app/static/')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.UserInfo')),
                ('nombreFotoPerfil', models.CharField(max_length=50)),
                ('archivoFotoPerfil', models.ImageField(upload_to='app/static/')),
            ],
        ),
        migrations.AddField(
            model_name='favoritos',
            name='alumno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.UserInfo'),
        ),
        migrations.CreateModel(
            name='VendedorAmbulante',
            fields=[
                ('vendedor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Vendedor')),
            ],
            bases=('app.vendedor',),
        ),
        migrations.CreateModel(
            name='VendedorFijo',
            fields=[
                ('vendedor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Vendedor')),
            ],
            bases=('app.vendedor',),
        ),
        migrations.AddField(
            model_name='productos',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Vendedor'),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='favorito',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Vendedor'),
        ),
    ]
