# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_productos_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='user',
            field=models.OneToOneField(default='admin', on_delete=django.db.models.deletion.CASCADE, to='app.Vendedor'),
            preserve_default=False,
        ),
    ]
