# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_productos_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendedorfijo',
            name='apertura',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='vendedorfijo',
            name='cierre',
            field=models.TimeField(default='00:00'),
        ),
    ]
